language: node_js
node_js:
  - "node"
env:
  - VERSION='^0.14.0'
  - VERSION='^15.0.0'
install:
  - npm install
  - npm install react@$VERSION react-dom@$VERSION react-addons-test-utils@$VERSION
  - npm install -g istanbul@1.1.0-alpha.1
script:
  - npm run cover
after_success:
  - npm install -g codecov
  - codecov
